### ISSUE TITLE
Cannot copy to a TensorFlowLite tensor (conv2d_input) with 16384 bytes from a Java Buffer with 49152 bytes.

### ISSUE THREAD

**Issue by priyanshnama** [priyanshnama/TF-Droid#2]
**Describe the bug**
Input size mismatch between tflite model and java buffer.

**To Reproduce**
1. Click on drop down.
2. Choose "Identify Number"
3. click on "Choose Image"
4.Choose and image and click Predict.
5. the app crashes at this point with error same as title the error log is attached below.
```java
2020-09-24 22:15:36.828 19961-19961/com.priyanshnama.tf_droid E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.priyanshnama.tf_droid, PID: 19961
    java.lang.IllegalStateException: Could not execute method for android:onClick
        at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:414)
        at android.view.View.performClick(View.java:6312)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:992)
        at android.view.View$PerformClick.run(View.java:24943)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:192)
        at android.app.ActivityThread.main(ActivityThread.java:6754)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:409)
        at android.view.View.performClick(View.java:6312) 
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:992) 
        at android.view.View$PerformClick.run(View.java:24943) 
        at android.os.Handler.handleCallback(Handler.java:790) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:192) 
        at android.app.ActivityThread.main(ActivityThread.java:6754) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828) 
     Caused by: java.lang.IllegalArgumentException: Cannot copy to a TensorFlowLite tensor (conv2d_input) with 16384 bytes from a Java Buffer with 49152 bytes.
        at org.tensorflow.lite.Tensor.throwIfSrcShapeIsIncompatible(Tensor.java:444)
        at org.tensorflow.lite.Tensor.setTo(Tensor.java:189)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:159)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:360)
        at org.tensorflow.lite.Interpreter.run(Interpreter.java:319)
        at com.priyanshnama.tf_droid.Classifier.recognizeImage(Classifier.kt:66)
        at com.priyanshnama.tf_droid.MainActivity.predict(MainActivity.kt:74)
        at java.lang.reflect.Method.invoke(Native Method) 
        at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:409) 
        at android.view.View.performClick(View.java:6312) 
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:992) 
        at android.view.View$PerformClick.run(View.java:24943) 
        at android.os.Handler.handleCallback(Handler.java:790) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:192) 
        at android.app.ActivityThread.main(ActivityThread.java:6754) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828) 
```` 

**Expected behavior**
The app should predict the number shown by fingers and output the same to user as a toast.

**Additional context**
try to manage size of image in MainActivity file.

**Comment by shivamsouravjha** [comment]
@heythere12 our project is stuck here, could you help?

**Comment by heythere12** [comment]
@shivamsouravjha I'll surely have a look and get back to you.


Thanks
Nishi

**Comment by priyanshnama** [comment]
### @heythere12  Models files are added. you can have a look at them.
**Possible Solution**
Try to add a bunch of code in [model file](https://github.com/ROBOTICS-CLUB-IIITDMJ/TF-Droid/blob/master/models/sign_language_digits_dataset_with_99_61_accuracy.ipynb) which shall convert the image (of any given size) to size (64 X 64) Required by the Project.

**Comment by shivamsouravjha** [comment]
@priyanshnama I've told you many times this is not how it's done 🤦‍♂️tflite download the already made up structure of model it can't config shape changed.

Model is made on shape of a dataset and can't be tempered as well,to my best knowledge it is work for Android part.

**Comment by shivamsouravjha** [comment]
@priyanshnama I've told you many times this is not how it's done 🤦‍♂️tflite download the already made up structure of model it can't config shape changed.

Model is made on shape of a dataset and can't be tempered as well,to my best knowledge it is work for Android part.

**Comment by shivamsouravjha** [comment]
@priyanshnama I've told you many times this is not how it's done 🤦‍♂️tflite download the already made up structure of model it can't config shape changed.

Model is made on shape of a dataset and can't be tempered as well,to my best knowledge it is work for Android part.

**Comment by shivamsouravjha** [comment]
@priyanshnama I've told you many times this is not how it's done 🤦‍♂️tflite download the already made up structure of model it can't config shape changed.

Model is made on shape of a dataset and can't be tempered as well,to my best knowledge it is work for Android part.
